# Generated by Django 5.2.4 on 2025-11-14 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=None, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Is Delete')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
