# Generated by Django 5.2.4 on 2025-11-14 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatar_images/', verbose_name='Avatar Image')),
                ('username', models.CharField(blank=True, max_length=300, null=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='PomodoroOrphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_minute', models.PositiveIntegerField(blank=True, null=True, verbose_name='Count Minute')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_pomodoro_orphan', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
