# Generated by Django 5.2.4 on 2025-11-14 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomodoro_duration', models.PositiveIntegerField(default=25, verbose_name='Pomodoro Duration')),
                ('short_relax_duration', models.PositiveIntegerField(default=5, verbose_name='Short Relax Duration')),
                ('long_relax_duration', models.PositiveIntegerField(default=15, verbose_name='Long Relax Duration')),
                ('interval_long_relax', models.PositiveIntegerField(default=4, verbose_name='Interval Long Relax')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_setting', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Pomodoro Setting',
                'verbose_name_plural': 'Pomodoro Settings',
            },
        ),
    ]
