# Generated by Django 5.2.4 on 2025-11-14 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=None, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('count_times', models.PositiveIntegerField(blank=True, null=True, verbose_name='Count Times')),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('hight', 'hight'), ('critical', 'critical')], default='low', max_length=50, verbose_name='Priority')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Is Delete')),
                ('date_type', models.CharField(choices=[('today', 'today'), ('tomorrow', 'tomorrow'), ('week', 'week'), ('planned', 'planned'), ('all', 'all')], default='today', max_length=50, verbose_name='Date Type')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project', verbose_name='Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TomatoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('work', 'work'), ('shortBreak', 'shortBreak'), ('longBreak', 'longBreak')], default='work', max_length=50, verbose_name='Mode')),
                ('pomodoro_duration', models.PositiveIntegerField(blank=True, default=25, null=True, verbose_name='Pomodoro Duration')),
                ('end_time_pomodoro', models.PositiveIntegerField(blank=True, null=True, verbose_name='End Time Pomodoro')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomato_history_task', to='task.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Tomato History',
                'verbose_name_plural': 'Tomato Histories',
            },
        ),
    ]
